theme: jekyll-theme-minimal
title: Jonas Weimar
description: ML, Data, Software Engineering and more
avatar: https://avatars.githubusercontent.com/u/38507420?s=400&u=59d6544e9e2548c13877e72857374c2e473bcfdf&v=4
